//[name, majorCategory, middleCategory, minorCategory, releaseDate, price, nation, status, isCollected, remarks, imageUrl]
var arr = [
  ['메이플스토리DS+닌텐도 DSi 스페셜 에디션','닌텐도','DS','DSHW','2010.04.15','237000₩','KR','미보유','N','DSi','/resource/image/nintendo/DS/KOR/Hardware/dsimaple.jpg'],
  ['닌텐도 DSi 레시라무･제크로무 에디션 <블랙>','닌텐도','DS','DSHW','2011.04.21','227000₩','KR','개봉','Y','DSi','/resource/image/nintendo/DS/KOR/Hardware/dsipokemonblack.jpg'],
  ['닌텐도 DSi 레시라무･제크로무 에디션 <화이트>','닌텐도','DS','DSHW','2011.04.21','227000₩','KR','개봉','Y','DSi','/resource/image/nintendo/DS/KOR/Hardware/dsipokemonwhite.jpg'],
  ['뉴 슈퍼 마리오브라더스 Wii 패키지','닌텐도','Wii','WiiHW','2010.12.11','188000₩','KR','미보유','Y','Wii','/resource/image/nintendo/Wii/KOR/Hardware/wii_mario_package.jpg'],
  ['마리오와 소닉 베이징 올림픽','닌텐도','Wii','WiiSW','2008.05.29','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_mario_sonic.jpg'],
  ['닌텐도 3DS XL 피카츄 옐로 패키지','닌텐도','3DS','3DSHW','2012.12.13','278000₩','KR','개봉','Y','3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/닌텐도 3DS XL 피카츄 옐로 패키지.jpg'],
['닌텐도 3DS XL 튀어나와요 동물의 숲 패키지','닌텐도','3DS','3DSHW','2013.02.07','318000₩','KR','미보유','Y','3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/닌텐도 3DS XL 튀어나와요 동물의 숲 패키지.jpg'],
['닌텐도 3DS XL 젤다의 전설 신들의 트라이포스 2 패키지','닌텐도','3DS','3DSHW','2014.06.21','270000₩','KR','개봉','Y','3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/닌텐도 3DS XL 젤다의 전설 신들의 트라이포스 2 패키지.jpg'],
['닌텐도 3DS XL 뉴 슈퍼 마리오브라더스 2 골드 에디션 패키지','닌텐도','3DS','3DSHW','2014.08.28','265000₩','KR','미보유','Y','3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/닌텐도 3DS XL 뉴 슈퍼 마리오브라더스 2 골드 에디션 패키지.jpg'],
['닌텐도 3DS XL 페르소나 Q 섀도우 오브 더 래버린스 벨벳 모델','닌텐도','3DS','3DSHW','2014.10.23','230000₩','KR','미보유','','3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/닌텐도 3DS XL 페르소나 Q 섀도우 오브 더 래버린스 벨벳 모델.jpg'],
['New 닌텐도 3DS XL 몬스터헌터 4G 에디션','닌텐도','3DS','3DSHW','2015.05.01','235000₩','KR','미보유','','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 몬스터헌터 4G 에디션.jpg'],
['New 닌텐도 3DS 마리오 스페셜 에디션','닌텐도','3DS','3DSHW','2015.09.10','188000₩','KR','개봉','Y','New 3DS','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS 마리오 스페셜 에디션.jpg'],
['New 닌텐도 3DS 지바냥 스페셜 에디션','닌텐도','3DS','3DSHW','2015.11.26','188000₩','KR','미보유','','New 3DS','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS 지바냥 스페셜 에디션.jpg'],
['New 닌텐도 3DS XL 하이랄 에디션','닌텐도','3DS','3DSHW','2016.01.28','235000₩','KR','개봉','Y','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 하이랄 에디션.jpg'],
['New 닌텐도 3DS XL 파이어 엠블렘 if 에디션','닌텐도','3DS','3DSHW','2016.09.08','235000₩','KR','단품','Y','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 파이어 엠블렘 if 에디션.jpg'],
['New 닌텐도 3DS XL 솔가레오・루나아라 포켓몬스터 썬 패키지','닌텐도','3DS','3DSHW','2016.11.18','279000₩','KR','개봉','Y','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 솔가레오・루나아라 포켓몬스터 썬 패키지.png'],
['New 닌텐도 3DS XL 솔가레오・루나아라 포켓몬스터 문 패키지','닌텐도','3DS','3DSHW','2016.11.18','279000₩','KR','미보유','Y','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 솔가레오・루나아라 포켓몬스터 문 패키지.jpg'],
[' New 닌텐도 3DS 동물의 숲 스페셜 에디션','닌텐도','3DS','3DSHW','2016.12.01','188000₩','KR','미보유','Y','New 3DS','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS 동물의 숲 스페셜 에디션.jpg'],
['New 닌텐도 3DS XL 피카츄 에디션','닌텐도','3DS','3DSHW','2017.03.04','235000₩','KR','미개봉','Y','New 3DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 3DS XL 피카츄 에디션.jpg'],
['New 닌텐도 2DS XL 몬스터볼 에디션','닌텐도','3DS','3DSHW','2017.11.17','175000₩','KR','개봉','Y','New 2DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 2DS XL 몬스터볼 에디션.jpg'],
['New 닌텐도 2DS XL 피카츄 에디션','닌텐도','3DS','3DSHW','2018.02.08','175000₩','KR','개봉','Y','New 2DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 2DS XL 피카츄 에디션.jpg'],
['Nintendo Switch 슈퍼 마리오 오디세이 세트','닌텐도','SWITCH','SWITCHHW','2018.04.26','445000₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 슈퍼 마리오 오디세이 세트.png'],
['Nintendo Switch 휴대용 케이스 슈퍼 마리오 오디세이 에디션','닌텐도','SWITCH','SWITCHHW','2018.04.26','27800₩','KR','미개봉','Y','Switch 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 휴대용 케이스 슈퍼 마리오 오디세이 에디션.jpg'],
['New 닌텐도 2DS XL 튀어나와요 동물의 숲 amiibo+ 패키지','닌텐도','3DS','3DSHW','2018.07.19','185000₩','KR','미개봉','Y','New 2DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 2DS XL 튀어나와요 동물의 숲 amiibo+ 패키지.jpg'],
['New 닌텐도 2DS XL 마리오 카트 7 패키지','닌텐도','3DS','3DSHW','2018.09.13','185000₩','KR','미개봉','Y','New 2DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 2DS XL 마리오 카트 7 패키지.jpg'],
['Nintendo Switch 포켓몬스터 Let\'s Go! 피카츄 세트','닌텐도','SWITCH','SWITCHHW','2018.11.16','464800₩','KR','미개봉','Y','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 포켓몬스터 Let\'s Go! 피카츄 세트.jpg'],
['Nintendo Switch 포켓몬스터 Let\'s Go! 이브이 세트','닌텐도','SWITCH','SWITCHHW','2018.11.16','464800₩','KR','미보유','Y','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 포켓몬스터 Let\'s Go! 이브이 세트.png'],
['New 닌텐도 2DS XL 하일리아의 방패 에디션','닌텐도','3DS','3DSHW','2018.11.29','165000₩','KR','미개봉','Y','New 2DS XL','/resource/image/nintendo/3DS/KOR/Hardware/New 닌텐도 2DS XL 하일리아의 방패 에디션.jpg'],
['Nintendo Switch 슈퍼 스매시브라더스 얼티밋 세트','닌텐도','SWITCH','SWITCHHW','2018.12.07','424800₩','KR','개봉','Y','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 슈퍼 스매시브라더스 얼티밋 세트.png'],
['Nintendo Switch Pro 컨트롤러 슈퍼 스매시브라더스 얼티밋 에디션','닌텐도','SWITCH','SWITCHHW','2018.12.07','79800₩','KR','미개봉','Y','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 슈퍼 스매시브라더스 얼티밋 에디션.jpg'],
['Nintendo Switch Pro 컨트롤러 Splatoon 2 에디션','닌텐도','SWITCH','SWITCHHW','2019.05.02','79800₩','KR','미개봉','Y','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 Splatoon 2 에디션.jpg'],
['Nintendo Switch 휴대용 케이스 Splatoon 2 에디션','닌텐도','SWITCH','SWITCHHW','2019.05.02','27800₩','KR','미개봉','Y','Switch 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 휴대용 케이스 Splatoon 2 에디션.jpg'],
['Nintendo Switch Lite 자시안・자마젠타 에디션','닌텐도','SWITCH','SWITCHHW','2019.11.01','249800₩','KR','미개봉','Y','Switch Lite','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite 자시안・자마젠타 에디션.png'],
['Nintendo Switch 마리오 카트 8 디럭스 세트','닌텐도','SWITCH','SWITCHHW','2019.11.28','369800₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 마리오 카트 8 디럭스 세트.png'],
['Nintendo Switch 모여봐요 동물의 숲 에디션','닌텐도','SWITCH','SWITCHHW','2020.03.20','360000₩','KR','미보유','Y','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 모여봐요 동물의 숲 에디션.png'],
['Nintendo Switch Lite 휴대용 케이스 모여봐요 동물의 숲 알로하 에디션','닌텐도','SWITCH','SWITCHHW','2020.03.20','27800₩','KR','미개봉','Y','Switch Lite 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite 휴대용 케이스 모여봐요 동물의 숲 알로하 에디션.jpg'],
['Nintendo Switch 휴대용 케이스 모여봐요 동물의 숲 알로하 에디션','닌텐도','SWITCH','SWITCHHW','2020.03.20','27800₩','KR','미보유','Y','Switch 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 휴대용 케이스 모여봐요 동물의 숲 알로하 에디션.jpg'],
['Nintendo Switch Pro 컨트롤러 제노블레이드 크로니클스 2 에디션','닌텐도','SWITCH','SWITCHHW','2020.09.03','79800₩','KR','미개봉','Y','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 제노블레이드 크로니클스 2 에디션.jpg'],
['Nintendo Switch 포트나이트 스페셜 세트','닌텐도','SWITCH','SWITCHHW','2020.10.30','360000₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 포트나이트 스페셜 세트.png'],
['Game&Watch 슈퍼 마리오브라더스','닌텐도','G&W','G&W','2020.11.13','54800₩','KR','개봉','Y','Game&Watch','/resource/image/nintendo/G&W/KOR/Hardware/Game&Watch 슈퍼 마리오브라더스.jpg'],
['Nintendo Switch 링 피트 어드벤처 세트','닌텐도','SWITCH','SWITCHHW','2020.12.03','444800₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 링 피트 어드벤처 세트.png'],
['Nintendo Switch 마리오 레드X블루 세트','닌텐도','SWITCH','SWITCHHW','2021.02.12','360000₩','KR','미개봉','Y','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 마리오 레드X블루 세트.png'],
['Nintendo Switch MONSTER HUNTER RISE 디럭스 에디션 세트','닌텐도','SWITCH','SWITCHHW','2021.03.26','449000₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch MONSTER HUNTER RISE 디럭스 에디션 세트.png'],
['Nintendo Switch Pro 컨트롤러 MONSTER HUNTER RISE 에디션','닌텐도','SWITCH','SWITCHHW','2021.03.26','79800₩','KR','미보유','N','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 MONSTER HUNTER RISE 에디션.jpg'],
['Joy-Con(L)/(R) 젤다의 전설 스카이워드 소드 에디션','닌텐도','SWITCH','SWITCHHW','2021.07.16','84800₩','KR','미개봉','Y','Joy-Con(L)/(R) ','/resource/image/nintendo/SWITCH/KOR/Hardware/Joy-Con(L)(R) 젤다의 전설 스카이워드 소드 에디션.jpg'],
['Nintendo Switch Lite 디아루가 펄기아 에디션','닌텐도','SWITCH','SWITCHHW','2021.11.05','249800₩','KR','미개봉','Y','Switch Lite','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite 디아루가 펄기아 에디션.png'],
['Game&Watch 젤다의 전설','닌텐도','G&W','G&W','2021.11.12','54800₩','KR','미개봉','Y','Game&Watch','/resource/image/nintendo/G&W/KOR/Hardware/Game&Watch 젤다의 전설.jpg'],
['Nintendo Switch Pro 컨트롤러 MONSTER HUNTER RISE: SUNBREAK 에디션','닌텐도','SWITCH','SWITCHHW','2022.06.30','79800₩','KR','미보유','N','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 MONSTER HUNTER RISE SUNBREAK 에디션.jpg'],
['Nintendo Switch (OLED 모델) 스플래툰 3 에디션','닌텐도','SWITCH','SWITCHHW','2022.08.26','425000₩','KR','미보유','Y','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch (OLED 모델) 스플래툰 3 에디션.jpg'],
['Nintendo Switch Pro 컨트롤러 스플래툰 3 에디션','닌텐도','SWITCH','SWITCHHW','2022.08.26','79800₩','KR','미개봉','Y','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 스플래툰 3 에디션.jpg'],
['Nintendo Switch 휴대용 케이스 스플래툰 3 에디션','닌텐도','SWITCH','SWITCHHW','2022.08.26','27800₩','KR','미개봉','Y','Switch 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 휴대용 케이스 스플래툰 3 에디션.jpg'],
['Nintendo Switch (OLED 모델) 스칼렛・바이올렛 에디션','닌텐도','SWITCH','SWITCHHW','2022.11.04','425000₩','KR','미개봉','Y','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch (OLED 모델) 스칼렛・바이올렛 에디션.jpg'],
['Nintendo Switch Nintendo Switch Sports 세트','닌텐도','SWITCH','SWITCHHW','2023.04.13','414800₩','KR','미보유','N','Switch','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Nintendo Switch Sports 세트.png'],
['Nintendo Switch (OLED 모델) 젤다의 전설 티어스 오브 더 킹덤 에디션','닌텐도','SWITCH','SWITCHHW','2023.04.28','425000₩','KR','미보유','Y','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch (OLED 모델) 젤다의 전설 티어스 오브 더 킹덤 에디션.jpg'],
['Nintendo Switch Pro 컨트롤러 젤다의 전설 티어스 오브 더 킹덤 에디션','닌텐도','SWITCH','SWITCHHW','2023.05.12','79800₩','KR','미개봉','Y','Switch Pro 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Pro 컨트롤러 젤다의 전설 티어스 오브 더 킹덤 에디션.jpg'],
['Nintendo Switch 휴대용 케이스 젤다의 전설 티어스 오브 더 킹덤 에디션','닌텐도','SWITCH','SWITCHHW','2023.05.12','27800₩','KR','미보유','Y','Switch 휴대용 케이스','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch 휴대용 케이스 젤다의 전설 티어스 오브 더 킹덤 에디션.jpg'],
['Nintendo Switch (OLED 모델) 마리오 레드','닌텐도','SWITCH','SWITCHHW','2023.10.06','415000₩','KR','미개봉','Y','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch (OLED 모델) 마리오 레드.jpg'],
['Nintendo Switch Lite 모여봐요 동물의 숲 여울 알로하 세트','닌텐도','SWITCH','SWITCHHW','2023.10.06','249800₩','KR','미보유','Y','Switch Lite','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite 모여봐요 동물의 숲 여울 알로하 세트.png'],
['Nintendo Switch Lite 모여봐요 동물의 숲 콩돌이&밤돌이 알로하 세트','닌텐도','SWITCH','SWITCHHW','2023.10.06','249800₩','KR','미보유','Y','Switch Lite','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite 모여봐요 동물의 숲 콩돌이&밤돌이 알로하 세트.png'],
['Nintendo Switch(OLED 모델) 마리오 카트 8 디럭스 세트','닌텐도','SWITCH','SWITCHHW','2023.11.10','415000₩','KR','미보유','N','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch(OLED 모델) 마리오 카트 8 디럭스 세트.jpg'],
['Nintendo Switch Lite  하이랄 에디션','닌텐도','SWITCH','SWITCHHW','2024.09.26','259800₩','KR','미보유','Y','Switch Lite','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch Lite  하이랄 에디션.jpg'],
['Nintendo Switch(OLED 모델) 모여봐요 동물의 숲 세트','닌텐도','SWITCH','SWITCHHW','2024.10.24','415000₩','KR','미보유','N','Switch (OLED 모델)','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Switch(OLED 모델) 모여봐요 동물의 숲 세트.jpg'],
['Nintendo Entertainment System™ 컨트롤러','닌텐도','SWITCH','SWITCHHW','2019.12.11','64800₩','KR','미개봉','Y','Nintendo Switch Online 전용 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo Entertainment System™ 컨트롤러.jpg'],
['Super Nintendo Entertainment System™ 컨트롤러','닌텐도','SWITCH','SWITCHHW','2019.12.18','34800₩','KR','미개봉','Y','Nintendo Switch Online 전용 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Super Nintendo Entertainment System™ 컨트롤러.jpg'],
['Nintendo 64 컨트롤러','닌텐도','SWITCH','SWITCHHW','2021.10.26','54800₩','KR','미보유','Y','Nintendo Switch Online 전용 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/Nintendo 64 컨트롤러.jpg'],
['SEGA Mega Drive Fighting Pad 6B','닌텐도','SWITCH','SWITCHHW','2021.10.26','54800₩','KR','미보유','Y','Nintendo Switch Online 전용 컨트롤러','/resource/image/nintendo/SWITCH/KOR/Hardware/SEGA Mega Drive Fighting Pad 6B.jpg'],
['슈퍼 마리오 3D 랜드','닌텐도','3DS','3DSSW','2012.04.28','42000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/슈퍼 마리오 3D 랜드.jpg'],
['마리오 카트 7','닌텐도','3DS','3DSSW','2012.05.31','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 카트 7.jpg'],
['마리오와 소닉 런던 올림픽','닌텐도','3DS','3DSSW','2012.06.21','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오와 소닉 런던 올림픽.jpg'],
['슈퍼 포켓몬 대격돌','닌텐도','3DS','3DSSW','2012.07.12','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/3DS/KOR/Software/슈퍼 포켓몬 대격돌.jpg'],
['스타폭스 64 3D','닌텐도','3DS','3DSSW','2012.08.30','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/스타폭스 64 3D.jpg'],
['젤다의 전설 시간의 오카리나 3D','닌텐도','3DS','3DSSW','2012.09.27','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 시간의 오카리나 3D.jpg'],
['뉴 슈퍼 마리오 브라더스 2','닌텐도','3DS','3DSSW','2012.12.06','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/뉴 슈퍼 마리오 브라더스 2.jpg'],
['튀어나와요 동물의 숲','닌텐도','3DS','3DSSW','2013.02.07','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/튀어나와요 동물의 숲.jpg'],
['마리오 테니스 오픈','닌텐도','3DS','3DSSW','2013.04.18','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 테니스 오픈.jpg'],
['페이퍼 마리오: 스티커 스타','닌텐도','3DS','3DSSW','2013.06.06','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/페이퍼 마리오 스티커 스타.jpg'],
['루이지 맨션: 다크 문','닌텐도','3DS','3DSSW','2013.07.18','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/루이지 맨션 다크 문.jpg'],
['포켓몬스터 X','닌텐도','3DS','3DSSW','2013.10.12','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 X.jpg'],
['포켓몬스터 Y','닌텐도','3DS','3DSSW','2013.10.12','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 Y.jpg'],
['동키콩 리턴즈 3D','닌텐도','3DS','3DSSW','2013.12.07','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/동키콩 리턴즈 3D.jpg'],
['몬스터 헌터 4','닌텐도','3DS','3DSSW','2013.12.14','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/몬스터 헌터 4.jpg'],
['마리오&루이지 RPG 4: 드림 어드벤처','닌텐도','3DS','3DSSW','2014.01.16','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오&루이지 RPG 4 드림 어드벤처.jpg'],
['마리오 파티: 아일랜드 투어','닌텐도','3DS','3DSSW','2014.03.20','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 파티 아일랜드 투어.jpg'],
['별의 커비 트리플 디럭스','닌텐도','3DS','3DSSW','2014.04.17','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/별의 커비 트리플 디럭스.jpg'],
['마리오 골프 월드 투어','닌텐도','3DS','3DSSW','2014.05.01','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 골프 월드 투어.jpg'],
['젤다의 전설 신들의 트라이포스 2','닌텐도','3DS','3DSSW','2014.06.21','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 신들의 트라이포스 2.jpg'],
['친구모아 아파트','닌텐도','3DS','3DSSW','2014.07.17','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/친구모아 아파트.jpg'],
['포켓몬스터 오메가루비','닌텐도','3DS','3DSSW','2014.11.21','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 오메가루비.jpg'],
['포켓몬스터 알파사파이어','닌텐도','3DS','3DSSW','2014.11.21','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 알파사파이어.jpg'],
['요시 뉴 아일랜드','닌텐도','3DS','3DSSW','2014.12.04','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/요시 뉴 아일랜드.jpg'],
['몬스터 헌터 4G','닌텐도','3DS','3DSSW','2015.03.26','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/몬스터 헌터 4G.jpg'],
['포켓몬 아트 아카데미','닌텐도','3DS','3DSSW','2015.04.23','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬 아트 아카데미.jpg'],
['퍼즐앤드래곤 Z + 퍼즐앤드래곤 슈퍼 마리오브라더스 에디션','닌텐도','3DS','3DSSW','2015.05.01','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/퍼즐앤드래곤 Z + 퍼즐앤드래곤 슈퍼 마리오브라더스 에디션.jpg'],
['Super Smash Bros. for Nintendo 3DS','닌텐도','3DS','3DSSW','2015.09.10','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/Super Smash Bros. for Nintendo 3DS.jpg'],
['젤다의 전설 트라이포스 삼총사','닌텐도','3DS','3DSSW','2016.01.28','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 트라이포스 삼총사.jpg'],
['젤다무쌍 하이랄의 전설들','닌텐도','3DS','3DSSW','2016.04.21','59000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다무쌍 하이랄의 전설들.jpg'],
['별의 커비 로보보 플래닛','닌텐도','3DS','3DSSW','2016.04.28','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/별의 커비 로보보 플래닛.jpg'],
['마리오&루이지 RPG: 페이퍼 마리오 MIX','닌텐도','3DS','3DSSW','2016.05.26','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오&루이지 RPG 페이퍼 마리오 MIX.jpg'],
['마리오와 소닉 리우 올림픽','닌텐도','3DS','3DSSW','2016.06.23','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오와 소닉 리우 올림픽.jpg'],
['젤다의 전설 무쥬라의 가면 3D','닌텐도','3DS','3DSSW','2016.07.14','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 무쥬라의 가면 3D.jpg'],
['파이어 엠블렘 if','닌텐도','3DS','3DSSW','2016.09.08','69000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/파이어 엠블렘 if.jpg'],
['포켓몬스터 썬','닌텐도','3DS','3DSSW','2016.11.18','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 썬.jpg'],
['포켓몬스터 문','닌텐도','3DS','3DSSW','2016.11.18','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 문.jpg'],
['튀어나와요 동물의 숲 amiibo+','닌텐도','3DS','3DSSW','2016.12.01','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/튀어나와요 동물의 숲 amiibo+.jpg'],
['리듬 세상 더 베스트 플러스','닌텐도','3DS','3DSSW','2016.12.01','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/리듬 세상 더 베스트 플러스.jpg'],
['포치와! 요시 울리 월드','닌텐도','3DS','3DSSW','2017.03.04','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포치와! 요시 울리 월드.jpg'],
['마리오 파티: 스타 러시','닌텐도','3DS','3DSSW','2017.04.27','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 파티 스타 러시.jpg'],
['마리오 스포츠 슈퍼스타즈','닌텐도','3DS','3DSSW','2017.07.13','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오 스포츠 슈퍼스타즈.jpg'],
['파이어 엠블렘 Echoes 또 하나의 영웅왕 프리미엄 에디션','닌텐도','3DS','3DSSW','2017.07.13','74800₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/파이어 엠블렘 Echoes 또 하나의 영웅왕 프리미엄 에디션.jpg'],
['슈퍼 포켓몬 대격돌 Nintendo Selects','닌텐도','3DS','3DSSW','2017.07.13','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/슈퍼 포켓몬 대격돌 Nintendo Selects.jpg'],
['친구모아 아파트 Nintendo Selects','닌텐도','3DS','3DSSW','2017.07.13','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/친구모아 아파트 Nintendo Selects.jpg'],
['슈퍼 마리오 메이커 for Nintendo 3DS','닌텐도','3DS','3DSSW','2017.08.03','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/슈퍼 마리오 메이커 for Nintendo 3DS.jpg'],
['포켓몬스터 울트라썬','닌텐도','3DS','3DSSW','2017.11.17','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 울트라썬.jpg'],
['포켓몬스터 울트라문','닌텐도','3DS','3DSSW','2017.11.17','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/포켓몬스터 울트라문.jpg'],
['동키콩 리턴즈 3D Nintendo Selects','닌텐도','3DS','3DSSW','2017.12.07','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/동키콩 리턴즈 3D Nintendo Selects.jpg'],
['요시 뉴 아일랜드 Nintendo Selects','닌텐도','3DS','3DSSW','2017.12.07','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/요시 뉴 아일랜드 Nintendo Selects.jpg'],
['커비 배틀 디럭스!','닌텐도','3DS','3DSSW','2018.02.01','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/커비 배틀 디럭스!.jpg'],
['마리오&루이지 RPG 1 DX','닌텐도','3DS','3DSSW','2018.04.12','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/마리오&루이지 RPG 1 DX.jpg'],
['젤다의 전설 시간의 오카리나 3D Nintendo Selects','닌텐도','3DS','3DSSW','2018.07.19','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 시간의 오카리나 3D Nintendo Selects.jpg'],
['루이지 맨션: 다크 문 Nintendo Selects','닌텐도','3DS','3DSSW','2018.07.19','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/루이지 맨션 다크 문 Nintendo Selects.jpg'],
['별의 커비 트리플 디럭스 Nintendo Selects','닌텐도','3DS','3DSSW','2018.07.19','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/별의 커비 트리플 디럭스 Nintendo Selects.jpg'],
['튀어나와요 동물의 숲 amiibo+ Nintendo Selects','닌텐도','3DS','3DSSW','2018.07.19','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/튀어나와요 동물의 숲 amiibo+ Nintendo Selects.jpg'],
['Hey! 피크민','닌텐도','3DS','3DSSW','2018.08.09','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/Hey! 피크민.jpg'],
['루이지 맨션','닌텐도','3DS','3DSSW','2018.11.08','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/루이지 맨션.jpg'],
['젤다의 전설 신들의 트라이포스 2 Nintendo Selects','닌텐도','3DS','3DSSW','2018.11.29','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/젤다의 전설 신들의 트라이포스 2 Nintendo Selects.jpg'],
['리듬 세상 더 베스트 플러스 Nintendo Selects','닌텐도','3DS','3DSSW','2018.11.29','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/리듬 세상 더 베스트 플러스 Nintendo Selects.jpg'],
['슈퍼 마리오 메이커 for Nintendo 3DS Nintendo Selects','닌텐도','3DS','3DSSW','2018.11.29','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/슈퍼 마리오 메이커 for Nintendo 3DS Nintendo Selects.jpg'],
['털실 커비 이야기 플러스','닌텐도','3DS','3DSSW','2019.04.12','49000₩','KR','미개봉','Y','실물','/resource/image/nintendo/3DS/KOR/Software/털실 커비 이야기 플러스.jpg'],
['슈퍼 마리오 Wii 갤럭시 어드벤처','닌텐도','Wii','WiiSW','2008.09.04','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_supermario.jpg'],
['마리오 파티 8','닌텐도','Wii','WiiSW','2008.11.06','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_mario_party8.jpg'],
['슈퍼 페이퍼 마리오','닌텐도','Wii','WiiSW','2009.02.26','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_spm.jpg'],
['마리오 카트 Wii','닌텐도','Wii','WiiSW','2009.04.30','58000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_mario_cart.jpg'],
['춤춰라 메이드 인 와리오','닌텐도','Wii','WiiSW','2009.06.18','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_madeinwario.jpg'],
['젤다의 전설 황혼의 공주','닌텐도','Wii','WiiSW','2009.08.27','54000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_zelda_legend.jpg'],
['마리오와 소닉 밴쿠버 동계올림픽','닌텐도','Wii','WiiSW','2009.11.19','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_vancouverOlympic.jpg'],
['타운으로 놀러가요 동물의 숲','닌텐도','Wii','WiiSW','2010.01.28','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_wiianimal.jpg'],
['마리오 파워 사커','닌텐도','Wii','WiiSW','2010.03.18','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_mariopowersoccer.jpg'],
['대난투 스매시브라더스 X','닌텐도','Wii','WiiSW','2010.04.29','49000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_smashbrosx.jpg'],
['뉴 슈퍼 마리오 브라더스 Wii','닌텐도','Wii','WiiSW','2010.08.07','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_NSMB_Wii.jpg'],
['링크의 사격 트레이닝+Wii 재퍼','닌텐도','Wii','WiiSW','2010.10.28','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_Link_shoot_training.jpg'],
['슈퍼 마리오 25주년 스페셜 에디션','닌텐도','Wii','WiiSW','2010.12.11','30000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_m25th_special_edition.jpg'],
['슈퍼 마리오 Wii 2: 갤럭시 어드벤처 투게더','닌텐도','Wii','WiiSW','2011.01.20','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_smwii2_galaxy.jpg'],
['와리오 랜드 셰이킹','닌텐도','Wii','WiiSW','2011.04.14','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_warioland.jpg'],
['털실 커비 이야기','닌텐도','Wii','WiiSW','2011.09.01','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_kirby_yarn.jpg'],
['피크민','닌텐도','Wii','WiiSW','2011.10.27','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_pikmin.jpg'],
['젤다의 전설 스카이워드 소드 ','닌텐도','Wii','WiiSW','2011.11.24','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_zelda_sword.jpg'],
['젤다의 전설 스카이워드 소드 젤다 25주년 패키지','닌텐도','Wii','WiiSW','2011.11.24','68000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/zelda25.jpg'],
['마리오와 소닉 런던 올림픽','닌텐도','Wii','WiiSW','2012.06.21','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_mslOlympic2012.jpg'],
['별의 커비 Wii','닌텐도','Wii','WiiSW','2012.09.06','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_starkirbyWii.jpg'],
['마리오 파티 9','닌텐도','Wii','WiiSW','2013.04.11','44000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_marioparty9.jpg'],
['리듬세상 Wii','닌텐도','Wii','WiiSW','2013.09.12','44000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/goods_somj.jpg'],
['마리오 카트 Wii Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','48000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/mario_kart_img.jpg'],
['타운으로 놀러가요 동물의 숲 Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','29000₩','KR','미보유','Y','실물','/resource/image/nintendo/Wii/KOR/Software/animal_img.jpg'],
['마리오 파워 사커 Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/soccor_img.jpg'],
['대난투 스매시브라더스 X Nintendo Selects','닌텐도','Wii','WiiSW','2014.11.06','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/smash_img.jpg'],
['슈퍼 마리오 Wii 갤럭시 어드벤처 Nintendo Selects','닌텐도','Wii','WiiSW','2015.04.23','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/supermario_img.jpg'],
['털실 커비 이야기 Nintendo Selects','닌텐도','Wii','WiiSW','2015.04.23','29000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/kirby_yarn_img.jpg'],
['젤다의 전설 황혼의 공주 Nintendo Selects','닌텐도','Wii','WiiSW','2015.08.06','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/Wii/KOR/Software/zelda_img.jpg'],
  ['뉴 슈퍼 마리오브라더스','닌텐도','DS','DSSW','2007.03.08','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_mario.gif'],
  ['포켓몬 대시','닌텐도','DS','DSSW','2007.03.22','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pocket.gif'],
  ['마리오 카트 DS','닌텐도','DS','DSSW','2007.04.05','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_mariokart.gif'],
  ['포켓몬 토로제','닌텐도','DS','DSSW','2007.05.17','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_toroje.gif'],
  ['만져라 메이드 인 와리오','닌텐도','DS','DSSW','2007.06.14','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_wario.gif'],
  ['테트리스 DS','닌텐도','DS','DSSW','2007.07.07','20000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_tetrisDS.gif'],
  ['슈퍼 마리오 64 DS','닌텐도','DS','DSSW','2007.07.26','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_mario64.gif'],
  ['포켓몬 불가사의 던전 파랑 구조대','닌텐도','DS','DSSW','2007.08.30','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pocketblue.gif'],
  ['별의 커비 도팡 일당의 습격','닌텐도','DS','DSSW','2007.09.13','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_star.gif'],
  ['숫자로 찾는 그림 퍼즐 피크로스 DS','닌텐도','DS','DSSW','2007.09.20','20000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_picrossDS.gif'],
  ['도와줘! 리듬 히어로','닌텐도','DS','DSSW','2007.10.11','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_rhythm.gif'],
  ['요시 아일랜드 DS','닌텐도','DS','DSSW','2007.11.08','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_yoshi.gif'],
  ['메트로이드 프라임 헌터즈','닌텐도','DS','DSSW','2007.12.06','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_metroid.gif'],
  ['놀러오세요 동물의 숲','닌텐도','DS','DSSW','2007.12.06','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_animal.gif'],
  ['포켓몬스터DP 디아루가','닌텐도','DS','DSSW','2008.02.14','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_dia.jpg'],
  ['포켓몬스터DP 펄기아','닌텐도','DS','DSSW','2008.02.14','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_pea.jpg'],
  ['젤다의 전설 몽환의 모래시계','닌텐도','DS','DSSW','2008.04.03','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/zelda.jpg'],
  ['마리오 파티 DS','닌텐도','DS','DSSW','2008.05.22','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/mario_party.jpg'],
  ['마리오와 소닉 베이징 올림픽','닌텐도','DS','DSSW','2008.06.26','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/msOlympic.jpg'],
  ['별의 커비 울트라 슈퍼 디럭스','닌텐도','DS','DSSW','2008.11.13','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/starkirby.jpg'],
  ['포켓몬 불가사의 던전 시간의 탐험대','닌텐도','DS','DSSW','2008.12.11','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pockettime.jpg'],
  ['포켓몬 불가사의 던전 어둠의 탐험대','닌텐도','DS','DSSW','2008.12.11','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pocketdark.jpg'],
  ['포켓몬스터Pt 기라티나','닌텐도','DS','DSSW','2009.07.02','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_PokemonPt.jpg'],
  ['리듬 세상','닌텐도','DS','DSSW','2009.09.24','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_rhythmworld.jpg'],
  ['마리오와 소닉 밴쿠버 동계 올림픽','닌텐도','DS','DSSW','2009.12.03','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_vancouverOlympic.jpg'],
  ['포켓몬스터 하트골드','닌텐도','DS','DSSW','2010.02.04','49000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pokemon_heartgold.jpg'],
  ['포켓몬스터 소울실버','닌텐도','DS','DSSW','2010.02.04','49000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/tab01_pokemon_soulsilver.jpg'],
  ['마리오&루이지 RPG 시간의 파트너','닌텐도','DS','DSSW','2010.07.08','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/RPG_time_partner.jpg'],
  ['포켓몬스터 블랙','닌텐도','DS','DSSW','2011.04.21','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_black.jpg'],
  ['포켓몬스터 화이트','닌텐도','DS','DSSW','2011.04.21','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_white.jpg'],
  ['마리오&루이지 RPG 3 쿠파 몸속 대모험','닌텐도','DS','DSSW','2011.07.21','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/mario_luigi_rpg3.jpg'],
  ['모여라! 커비','닌텐도','DS','DSSW','2011.12.01','33000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/atsumete_kirby.jpg'],
  ['포켓몬스터 블랙 2','닌텐도','DS','DSSW','2011.11.08','39000₩','KR','미개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_black2.jpg'],
  ['포켓몬스터 화이트 2','닌텐도','DS','DSSW','2011.11.08','39000₩','KR','개봉','Y','실물','/resource/image/nintendo/DS/KOR/Software/pokemon_white2.jpg']
  ]; 
