//[name, majorCategory, middleCategory, minorCategory, releaseDate, price, nation, status, isCollected, remarks, imageUrl]
var arr = [
  ['메이플스토리DS+닌텐도 DSi 스페셜 에디션','닌텐도','DS','DSHW','2010.04.15','237000₩','KR','미보유','N','-','/resource/image/nintendo/DS/KOR/Hardware/dsimaple.jpg'],
  ['닌텐도 DSi 레시라무･제크로무 에디션 <블랙>','닌텐도','DS','DSHW','2011.04.21','227000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Hardware/dsipokemonblack.jpg'],
  ['닌텐도 DSi 레시라무･제크로무 에디션 <화이트>','닌텐도','DS','DSHW','2011.04.21','227000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Hardware/dsipokemonwhite.jpg'],
  ['마리오와 소닉 베이징 올림픽','닌텐도','Wii','WiiSW','2008.05.29','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_mario_sonic.jpg'],
  ['뉴 슈퍼 마리오브라더스 Wii 패키지','닌텐도','Wii','WiiHW','2010.12.11','188000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Hardware/wii_mario_package.jpg'],
['슈퍼 마리오 Wii 갤럭시 어드벤처','닌텐도','Wii','WiiSW','2008.09.04','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_supermario.jpg'],
['마리오 파티 8','닌텐도','Wii','WiiSW','2008.11.06','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_mario_party8.jpg'],
['슈퍼 페이퍼 마리오','닌텐도','Wii','WiiSW','2009.02.26','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_spm.jpg'],
['마리오 카트 Wii','닌텐도','Wii','WiiSW','2009.04.30','58000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_mario_cart.jpg'],
['춤춰라 메이드 인 와리오','닌텐도','Wii','WiiSW','2009.06.18','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_madeinwario.jpg'],
['젤다의 전설 황혼의 공주','닌텐도','Wii','WiiSW','2009.08.27','54000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_zelda_legend.jpg'],
['마리오와 소닉 밴쿠버 동계올림픽','닌텐도','Wii','WiiSW','2009.11.19','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_vancouverOlympic.jpg'],
['타운으로 놀러가요 동물의 숲','닌텐도','Wii','WiiSW','2010.01.28','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_wiianimal.jpg'],
['마리오 파워 사커','닌텐도','Wii','WiiSW','2010.03.18','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_mariopowersoccer.jpg'],
['대난투 스매시브라더스 X','닌텐도','Wii','WiiSW','2010.04.29','49000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_smashbrosx.jpg'],
['뉴 슈퍼 마리오 브라더스 Wii','닌텐도','Wii','WiiSW','2010.08.07','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_NSMB_Wii.jpg'],
['링크의 사격 트레이닝+Wii 재퍼','닌텐도','Wii','WiiSW','2010.10.28','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_Link_shoot_training.jpg'],
['슈퍼 마리오 25주년 스페셜 에디션','닌텐도','Wii','WiiSW','2010.12.11','30000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_m25th_special_edition.jpg'],
['슈퍼 마리오 Wii 2: 갤럭시 어드벤처 투게더','닌텐도','Wii','WiiSW','2011.01.20','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_smwii2_galaxy.jpg'],
['와리오 랜드 셰이킹','닌텐도','Wii','WiiSW','2011.04.14','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_warioland.jpg'],
['털실 커비 이야기','닌텐도','Wii','WiiSW','2011.09.01','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_kirby_yarn.jpg'],
['피크민','닌텐도','Wii','WiiSW','2011.10.27','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_pikmin.jpg'],
['젤다의 전설 스카이워드 소드 ','닌텐도','Wii','WiiSW','2011.11.24','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_zelda_sword.jpg'],
['젤다의 전설 스카이워드 소드 젤다 25주년 패키지','닌텐도','Wii','WiiSW','2011.11.24','68000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/zelda25.jpg'],
['마리오와 소닉 런던 올림픽','닌텐도','Wii','WiiSW','2012.06.21','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_mslOlympic2012.jpg'],
['별의 커비 Wii','닌텐도','Wii','WiiSW','2012.09.06','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_starkirbyWii.jpg'],
['마리오 파티 9','닌텐도','Wii','WiiSW','2013.04.11','44000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_marioparty9.jpg'],
['리듬세상 Wii','닌텐도','Wii','WiiSW','2013.09.12','44000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/goods_somj.jpg'],
['마리오 카트 Wii Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','48000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/mario_kart_img.jpg'],
['타운으로 놀러가요 동물의 숲 Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','29000₩','KR','미보유','Y','-','/resource/image/nintendo/Wii/KOR/Software/animal_img.jpg'],
['마리오 파워 사커 Nintendo Selects','닌텐도','Wii','WiiSW','2014.08.28','29000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/soccor_img.jpg'],
['대난투 스매시브라더스 X Nintendo Selects','닌텐도','Wii','WiiSW','2014.11.06','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/smash_img.jpg'],
['슈퍼 마리오 Wii 갤럭시 어드벤처 Nintendo Selects','닌텐도','Wii','WiiSW','2015.04.23','29000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/supermario_img.jpg'],
['털실 커비 이야기 Nintendo Selects','닌텐도','Wii','WiiSW','2015.04.23','29000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/kirby_yarn_img.jpg'],
['젤다의 전설 황혼의 공주 Nintendo Selects','닌텐도','Wii','WiiSW','2015.08.06','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/Wii/KOR/Software/zelda_img.jpg'],
  ['뉴 슈퍼 마리오브라더스','닌텐도','DS','DSSW','2007.03.08','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_mario.gif'],
  ['포켓몬 대시','닌텐도','DS','DSSW','2007.03.22','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pocket.gif'],
  ['마리오 카트 DS','닌텐도','DS','DSSW','2007.04.05','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_mariokart.gif'],
  ['포켓몬 토로제','닌텐도','DS','DSSW','2007.05.17','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_toroje.gif'],
  ['만져라 메이드 인 와리오','닌텐도','DS','DSSW','2007.06.14','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_wario.gif'],
  ['테트리스 DS','닌텐도','DS','DSSW','2007.07.07','20000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_tetrisDS.gif'],
  ['슈퍼 마리오 64 DS','닌텐도','DS','DSSW','2007.07.26','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_mario64.gif'],
  ['포켓몬 불가사의 던전 파랑 구조대','닌텐도','DS','DSSW','2007.08.30','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pocketblue.gif'],
  ['별의 커비 도팡 일당의 습격','닌텐도','DS','DSSW','2007.09.13','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_star.gif'],
  ['숫자로 찾는 그림 퍼즐 피크로스 DS','닌텐도','DS','DSSW','2007.09.20','20000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_picrossDS.gif'],
  ['도와줘! 리듬 히어로','닌텐도','DS','DSSW','2007.10.11','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_rhythm.gif'],
  ['요시 아일랜드 DS','닌텐도','DS','DSSW','2007.11.08','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_yoshi.gif'],
  ['메트로이드 프라임 헌터즈','닌텐도','DS','DSSW','2007.12.06','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_metroid.gif'],
  ['놀러오세요 동물의 숲','닌텐도','DS','DSSW','2007.12.06','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_animal.gif'],
  ['포켓몬스터DP 디아루가','닌텐도','DS','DSSW','2008.02.14','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_dia.jpg'],
  ['포켓몬스터DP 펄기아','닌텐도','DS','DSSW','2008.02.14','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_pea.jpg'],
  ['젤다의 전설 몽환의 모래시계','닌텐도','DS','DSSW','2008.04.03','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/zelda.jpg'],
  ['마리오 파티 DS','닌텐도','DS','DSSW','2008.05.22','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/mario_party.jpg'],
  ['마리오와 소닉 베이징 올림픽','닌텐도','DS','DSSW','2008.06.26','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/msOlympic.jpg'],
  ['별의 커비 울트라 슈퍼 디럭스','닌텐도','DS','DSSW','2008.11.13','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/starkirby.jpg'],
  ['포켓몬 불가사의 던전 시간의 탐험대','닌텐도','DS','DSSW','2008.12.11','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pockettime.jpg'],
  ['포켓몬 불가사의 던전 어둠의 탐험대','닌텐도','DS','DSSW','2008.12.11','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pocketdark.jpg'],
  ['포켓몬스터Pt 기라티나','닌텐도','DS','DSSW','2009.07.02','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_PokemonPt.jpg'],
  ['리듬 세상','닌텐도','DS','DSSW','2009.09.24','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_rhythmworld.jpg'],
  ['마리오와 소닉 밴쿠버 동계 올림픽','닌텐도','DS','DSSW','2009.12.03','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_vancouverOlympic.jpg'],
  ['포켓몬스터 하트골드','닌텐도','DS','DSSW','2010.02.04','49000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pokemon_heartgold.jpg'],
  ['포켓몬스터 소울실버','닌텐도','DS','DSSW','2010.02.04','49000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/tab01_pokemon_soulsilver.jpg'],
  ['마리오&루이지 RPG 시간의 파트너','닌텐도','DS','DSSW','2010.07.08','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/RPG_time_partner.jpg'],
  ['포켓몬스터 블랙','닌텐도','DS','DSSW','2011.04.21','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_black.jpg'],
  ['포켓몬스터 화이트','닌텐도','DS','DSSW','2011.04.21','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_white.jpg'],
  ['마리오&루이지 RPG 3 쿠파 몸속 대모험','닌텐도','DS','DSSW','2011.07.21','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/mario_luigi_rpg3.jpg'],
  ['모여라! 커비','닌텐도','DS','DSSW','2011.12.01','33000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/atsumete_kirby.jpg'],
  ['포켓몬스터 블랙 2','닌텐도','DS','DSSW','2011.11.08','39000₩','KR','미개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_black2.jpg'],
  ['포켓몬스터 화이트 2','닌텐도','DS','DSSW','2011.11.08','39000₩','KR','개봉','Y','-','/resource/image/nintendo/DS/KOR/Software/pokemon_white2.jpg']
  ]; 
